### ISSUE TITLE
did i build it correctly

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/woodwalkers-mod#38]
i built the mod to test the early version on java equips IDE i have used it before but the built version inst compatible with 1.2.3 crafted core , i tryed 1.3.0 but then remorphed was crashing when i joined the world, did i build it correctly?

**Comment by ToCraft** [comment]
Ye, you build it correctly. It just that I haven't found time to port Remorphed to CraftedCore 1.3, but I ported woodwalkers already.
Since I'm not in the same town as my setup rn, I'm not able to do this so easily, but, in case you're expierenced with git, you could just "drop" the commit which ports Woodwalkers to CraftedCore 1.3 and built it again.
Everything should run just fine then (with CraftedCore 1.2.3)

**Comment by ToCraft** [comment]
I just released CraftedCore 1.3.1, which adds backwards compatiblity to 1.2.3 so now it should work :D
